[package]
name = "mu"
version = "0.1.0"
edition = "2021"
description = "Control itunes from the command line"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
